### ISSUE TITLE
content is left-shifted

### ISSUE THREAD

**Issue by ClaytonJY** [GjjvdBurg/arxiv2remarkable#2]
Is it possible to have the output content not be left-shifted, but instead be in the center of the page? having everything against the left border looks unnatural, and means that in a RHS configuration the toolbars cover a lot of content when expanded.

(p.s. thanks for the great tool!)

**Comment by GjjvdBurg** [comment]
Hi @ClaytonJY, thanks for the suggestion! I've added a PR with a potential solution. Can you check if this works for you? I've checked it on two files and it seems to center the PDF on the screen. When you confirm it works, I'll merge it into master.

(note that this doesn't generally ensure the toolbar doesn't cover anything. I'm not sure what the math for that should be, so I'm open to suggestions there. It would probably require increasing the margins on all sides somehow)

**Comment by ClaytonJY** [comment]
Sorry I forgot to reply; I've been using this for awhile and it works great! Thank you very much for the quick fix here @GjjvdBurg.

**Comment by GjjvdBurg** [comment]
No problem, glad to hear it! Btw, since version 0.3.0 I'm using new cropping code because pdfcrop didn't always return the right bounding box. If you haven't already I recommend updating! :)
